In [57]:
def Croston(ts,extra_periods=1,alpha=0.4):
    d = np.array(ts) # Transform the input into a numpy array
    cols = len(d) # Historical period length
    d = np.append(d,[np.nan]*extra_periods) # Append np.nan into the demand array to cover future periods
    
    #level (a), periodicity(p) and forecast (f)
    a,p,f = np.full((3,cols+extra_periods),np.nan)
    q = 1 #periods since last demand observation
    
    # Initialization
    print(d[:cols])
    first_occurence = np.argmax(d[:cols]>0)
    a[0] = d[first_occurence]
    p[0] = 1 + first_occurence
    f[0] = a[0]/p[0]
# Create all the t+1 forecasts
    for t in range(0,cols):        
        if d[t] > 0:
            a[t+1] = alpha*d[t] + (1-alpha)*a[t] 
            p[t+1] = alpha*q + (1-alpha)*p[t]
            f[t+1] = a[t+1]/p[t+1]
            q = 1           
        else:
            a[t+1] = a[t]
            p[t+1] = p[t]
            f[t+1] = f[t]
            q += 1
       
    # Future Forecast 
    a[cols+1:cols+extra_periods] = a[cols]
    p[cols+1:cols+extra_periods] = p[cols]
    f[cols+1:cols+extra_periods] = f[cols]
                      
    df = pd.DataFrame.from_dict({"Demand":d,"Forecast":f,"Period":p,"Level":a,"Error":d-f})
    return df

def Croston_TSB(ts,extra_periods=1,alpha=0.4,beta=0.4):
    d = np.array(ts) # Transform the input into a numpy array
    cols = len(d) # Historical period length
    d = np.append(d,[np.nan]*extra_periods) # Append np.nan into the demand array to cover future periods
    
    #level (a), probability(p) and forecast (f)
    a,p,f = np.full((3,cols+extra_periods),np.nan)
# Initialization
    first_occurence = np.argmax(d[:cols]>0)
    a[0] = d[first_occurence]
    p[0] = 1/(1 + first_occurence)
    f[0] = p[0]*a[0]
                 
    # Create all the t+1 forecasts
    for t in range(0,cols): 
        if d[t] > 0:
            a[t+1] = alpha*d[t] + (1-alpha)*a[t] 
            p[t+1] = beta*(1) + (1-beta)*p[t]  
        else:
            a[t+1] = a[t]
            p[t+1] = (1-beta)*p[t]       
        f[t+1] = p[t+1]*a[t+1]
        
    # Future Forecast
    a[cols+1:cols+extra_periods] = a[cols]
    p[cols+1:cols+extra_periods] = p[cols]
    f[cols+1:cols+extra_periods] = f[cols]
                      
    df = pd.DataFrame.from_dict({"Demand":d,"Forecast":f,"Period":p,"Level":a,"Error":d-f})
    return df
def Croston(ts,extra_periods=1,alpha=0.4):
    d = np.array(ts) # Transform the input into a numpy array
    cols = len(d) # Historical period length
    d = np.append(d,[np.nan]*extra_periods) # Append np.nan into the demand array to cover future periods
    
    #level (a), periodicity(p) and forecast (f)
    a,p,f = np.full((3,cols+extra_periods),np.nan)
    q = 1 #periods since last demand observation
    
    # Initialization
    first_occurence = np.argmax(d[:cols]>0)
    a[0] = d[first_occurence]
    p[0] = 1 + first_occurence
    f[0] = a[0]/p[0]
# Create all the t+1 forecasts
    for t in range(0,cols):        
        if d[t] > 0:
            a[t+1] = alpha*d[t] + (1-alpha)*a[t] 
            p[t+1] = alpha*q + (1-alpha)*p[t]
            f[t+1] = a[t+1]/p[t+1]
            q = 1           
        else:
            a[t+1] = a[t]
            p[t+1] = p[t]
            f[t+1] = f[t]
            q += 1
       
    # Future Forecast 
    a[cols+1:cols+extra_periods] = a[cols]
    p[cols+1:cols+extra_periods] = p[cols]
    f[cols+1:cols+extra_periods] = f[cols]
                      
    df = pd.DataFrame.from_dict({"Demand":d,"Forecast":f,"Period":p,"Level":a,"Error":d-f})
    return df

In [68]:
import pandas as pd
import numpy as np
from datetime import datetime
# data = pd.read_csv("C:\\Users\\User\\Source Code\\data\\demand.csv")


import pandas as pd
from pandas.compat import StringIO

data = pd.read_csv("C:\\Users\\User\\Source Code\\data\\demand.csv",squeeze=True,index_col=[0],parse_dates=True,names=['Date','Amount'])

type(data)

pandas.core.series.Series

In [71]:
Croston(data,extra_periods=30,alpha=0.4)

     Demand   Forecast    Period      Level      Error
0       0.0  31.333333  3.000000  94.000000 -31.333333
1       0.0  31.333333  3.000000  94.000000 -31.333333
2      94.0  31.333333  3.000000  94.000000  62.666667
3       0.0  31.333333  3.000000  94.000000 -31.333333
4       0.0  31.333333  3.000000  94.000000 -31.333333
5      99.0  31.333333  3.000000  94.000000  67.666667
6      90.0  32.000000  3.000000  96.000000  58.000000
7       0.0  42.545455  2.200000  93.600000 -42.545455
8      43.0  42.545455  2.200000  93.600000   0.454545
9       0.0  34.603774  2.120000  73.360000 -34.603774
10      0.0  34.603774  2.120000  73.360000 -34.603774
11      0.0  34.603774  2.120000  73.360000 -34.603774
12      0.0  34.603774  2.120000  73.360000 -34.603774
13      0.0  34.603774  2.120000  73.360000 -34.603774
14     59.0  34.603774  2.120000  73.360000  24.396226
15     20.0  18.413943  3.672000  67.616000   1.586057
16      0.0  18.657652  2.603200  48.569600 -18.657652
17      0.0  18.657652  2.603200  48.569600 -18.657652
18     66.0  18.657652  2.603200  48.569600  47.342348
19      0.0  20.109837  2.761920  55.541760 -20.109837
20     15.0  20.109837  2.761920  55.541760  -5.109837
21      0.0  16.004324  2.457152  39.325056 -16.004324
22     76.0  16.004324  2.457152  39.325056  59.995676
23     96.0  23.741478  2.274291  53.995034  72.258522
24     35.0  40.121293  1.764575  70.797020  -5.121293
25      0.0  38.716992  1.458745  56.478212 -38.716992
26      0.0  38.716992  1.458745  56.478212 -38.716992
27      0.0  38.716992  1.458745  56.478212 -38.716992
28     26.0  38.716992  1.458745  56.478212 -12.716992
29      0.0  17.891923  2.475247  44.286927 -17.891923
..      ...        ...       ...        ...        ...
365     NaN  48.521035  1.154795  56.031858        NaN
366     NaN  48.521035  1.154795  56.031858        NaN
367     NaN  48.521035  1.154795  56.031858        NaN
368     NaN  48.521035  1.154795  56.031858        NaN
369     NaN  48.521035  1.154795  56.031858        NaN
370     NaN  48.521035  1.154795  56.031858        NaN
371     NaN  48.521035  1.154795  56.031858        NaN
372     NaN  48.521035  1.154795  56.031858        NaN
373     NaN  48.521035  1.154795  56.031858        NaN
374     NaN  48.521035  1.154795  56.031858        NaN
375     NaN  48.521035  1.154795  56.031858        NaN
376     NaN  48.521035  1.154795  56.031858        NaN
377     NaN  48.521035  1.154795  56.031858        NaN
378     NaN  48.521035  1.154795  56.031858        NaN
379     NaN  48.521035  1.154795  56.031858        NaN
380     NaN  48.521035  1.154795  56.031858        NaN
381     NaN  48.521035  1.154795  56.031858        NaN
382     NaN  48.521035  1.154795  56.031858        NaN
383     NaN  48.521035  1.154795  56.031858        NaN
384     NaN  48.521035  1.154795  56.031858        NaN
385     NaN  48.521035  1.154795  56.031858        NaN
386     NaN  48.521035  1.154795  56.031858        NaN
387     NaN  48.521035  1.154795  56.031858        NaN
388     NaN  48.521035  1.154795  56.031858        NaN
389     NaN  48.521035  1.154795  56.031858        NaN
390     NaN  48.521035  1.154795  56.031858        NaN
391     NaN  48.521035  1.154795  56.031858        NaN
392     NaN  48.521035  1.154795  56.031858        NaN
393     NaN  48.521035  1.154795  56.031858        NaN
394     NaN  48.521035  1.154795  56.031858        NaN

[395 rows x 5 columns]